-- CreateTable
CREATE TABLE "cinemas" (
    "ID" INTEGER NOT NULL,
    "CinemaNationalId" TEXT,
    "Name" TEXT NOT NULL,
    "NameAlt" TEXT NOT NULL,
    "PhoneNumber" TEXT NOT NULL,
    "EmailAddress" TEXT NOT NULL,
    "Address1" TEXT NOT NULL,
    "Address2" TEXT NOT NULL,
    "City" TEXT NOT NULL,
    "Latitude" DOUBLE PRECISION,
    "Longitude" DOUBLE PRECISION,
    "ParkingInfo" TEXT NOT NULL,
    "LoyaltyCode" TEXT NOT NULL,
    "IsGiftStore" BOOLEAN NOT NULL,
    "Description" TEXT NOT NULL,
    "DescriptionAlt" TEXT,
    "PublicTransport" TEXT NOT NULL,
    "CurrencyCode" TEXT,
    "AllowPrintAtHomeBookings" BOOLEAN NOT NULL,
    "AllowOnlineVoucherValidation" BOOLEAN NOT NULL,
    "DisplaySofaSeats" BOOLEAN NOT NULL,
    "TimeZoneId" TEXT NOT NULL,
    "HOPK" TEXT NOT NULL,
    "NameTranslations" JSONB NOT NULL,
    "DescriptionTranslations" JSONB NOT NULL,
    "ParkingInfoTranslations" JSONB NOT NULL,
    "PublicTransportTranslations" JSONB NOT NULL,
    "TipsCompulsory" BOOLEAN NOT NULL,
    "TipPercentages" TEXT NOT NULL,
    "ServerName" TEXT,
    "IsInTouchEnabled" BOOLEAN NOT NULL,
    "IsGetHelpEnabled" BOOLEAN NOT NULL,
    "PrimaryDataLanguage" TEXT,
    "AlternateDataLanguage1" TEXT,
    "AlternateDataLanguage2" TEXT,
    "AlternateDataLanguage3" TEXT,
    "HasConcessions" BOOLEAN NOT NULL,

    CONSTRAINT "cinemas_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "movies" (
    "ID" TEXT NOT NULL,
    "AdditionalUrls" JSONB NOT NULL,
    "ShortCode" TEXT NOT NULL,
    "Title" TEXT NOT NULL,
    "Rating" TEXT NOT NULL,
    "RatingDescription" TEXT NOT NULL,
    "Synopsis" TEXT,
    "SynopsisAlt" TEXT NOT NULL,
    "SynopsisTranslations" JSONB NOT NULL,
    "ShortSynopsis" TEXT,
    "HOFilmCode" TEXT NOT NULL,
    "CorporateFilmId" TEXT,
    "RunTime" INTEGER NOT NULL,
    "OpeningDate" TIMESTAMP(3),
    "GraphicUrl" TEXT NOT NULL,
    "FilmNameUrl" TEXT NOT NULL,
    "TrailerUrl" TEXT NOT NULL,
    "IsComingSoon" BOOLEAN NOT NULL,
    "IsScheduledAtCinema" BOOLEAN NOT NULL,
    "TitleAlt" TEXT NOT NULL,
    "RatingAlt" TEXT NOT NULL,
    "RatingDescriptionAlt" TEXT NOT NULL,
    "ShortSynopsisAlt" TEXT,
    "WebsiteUrl" TEXT NOT NULL,
    "GenreId" TEXT NOT NULL,
    "GenreId2" TEXT,
    "GenreId3" TEXT,
    "EDICode" TEXT,
    "FormatCodes" JSONB NOT NULL,
    "TwitterTag" TEXT NOT NULL,
    "TitleTranslations" JSONB NOT NULL,
    "ShortSynopsisTranslations" JSONB NOT NULL,
    "RatingDescriptionTranslations" JSONB NOT NULL,
    "CustomerRatingStatistics" JSONB NOT NULL,
    "CustomerRatingTrailerStatistics" JSONB NOT NULL,
    "FilmWebId" TEXT,
    "MovieXchangeCode" TEXT,
    "DistributorName" TEXT NOT NULL,
    "GovernmentCode" TEXT,

    CONSTRAINT "movies_pkey" PRIMARY KEY ("ID")
);
